"""add relationship between category and user

Revision ID: 512dc800bd38
Revises: 5dba619255a
Create Date: 2015-08-07 21:31:18.803329

"""

# revision identifiers, used by Alembic.
revision = '512dc800bd38'
down_revision = '5dba619255a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'user_id')
    ### end Alembic commands ###
